"""
Turn the hospital's filled workbook into a migration.

    python scripts/build_migration.py <workbook.xlsx> <output.sql>

Every statement is an upsert on the key named in content_schema.TABLES, so the
result is safe to run twice and safe to run after the team has edited a row by
hand in the admin: an unchanged cell writes an unchanged value.

Nothing is deleted. Rows that disappear from the workbook are left alone rather
than removed, because a blank sheet is far more often an oversight than an
instruction to unpublish a department.
"""

import sys
from pathlib import Path

import openpyxl

sys.path.insert(0, str(Path(__file__).parent))
from content_schema import TABLES, day_number, slugify, sql_str  # noqa: E402


def read_sheet(wb, sheet_name):
    """Rows as dicts, keyed by the header row. Blank rows are skipped."""
    if sheet_name not in wb.sheetnames:
        return []
    ws = wb[sheet_name]

    header_row = None
    for row in ws.iter_rows(min_row=1, max_row=12):
        values = [str(c.value).strip() if c.value is not None else "" for c in row]
        if sum(1 for v in values if v) >= 2 and any(v.islower() or "_" in v for v in values):
            header_row = row[0].row
            headers = values
            break
    if header_row is None:
        return []

    out = []
    for row in ws.iter_rows(min_row=header_row + 1, values_only=True):
        if not any(v not in (None, "") for v in row):
            continue
        record = {}
        for head, value in zip(headers, row):
            if head:
                record[head] = value
        out.append(record)
    return out


# A sheet says "department_slug"; the table stores a uuid. Resolved in SQL so the
# workbook never has to carry an id a person cannot read or check.
LOOKUPS = {
    "department_slug": ("department_id", "margaret_departments", "slug"),
    "clinic_slug": ("clinic_id", "margaret_clinics", "slug"),
}

# setting_value is jsonb; everything else is a plain literal.
CASTS = {"setting_value": "to_jsonb({}::text)"}

NUMERIC = {"sort_order", "day_of_week", "rating", "awarded_year", "years_experience"}


def render(column, value):
    """(column_name, sql_expression) for one cell."""
    if column in LOOKUPS:
        target, table, match = LOOKUPS[column]
        if value in (None, ""):
            return target, "null"
        return target, f"(select id from {table} where {match} = {sql_str(value)} limit 1)"

    if column == "day_of_week" and value not in (None, ""):
        return column, str(day_number(value))

    if column in ("start_time", "end_time"):
        return column, "null" if value in (None, "") else sql_str(str(value)[:8])

    if column in NUMERIC and value not in (None, ""):
        return column, str(value)

    literal = sql_str(value)
    if column in CASTS and literal != "null":
        return column, CASTS[column].format(literal)
    return column, literal


def upsert(table, key, columns, record):
    """
    Update-then-insert rather than ON CONFLICT.

    Only a few of these tables carry a unique index on the column that
    identifies a row to a person, and adding one to the rest would mean
    rejecting the hospital's own duplicates at import time instead of letting
    them fix it. This pattern needs no index and behaves the same.
    """
    keys = (key,) if isinstance(key, str) else key

    pairs = [render(c, record.get(c)) for c in columns]
    where = " and ".join(
        f"{c} = {expr}" for c, expr in pairs if c in keys
    )
    # A blank cell leaves the existing value alone. Clearing a field is done in
    # the admin, deliberately, not by leaving a cell empty in a spreadsheet.
    sets = ", ".join(
        f"{c} = coalesce({expr}, {c})" for c, expr in pairs if c not in keys
    )

    cols = ", ".join(c for c, _ in pairs)
    vals = ", ".join(expr for _, expr in pairs)

    return "\n".join([
        f"update {table} set {sets}, updated_at = now() where {where};",
        f"insert into {table} ({cols})",
        f"select {vals}",
        f"where not exists (select 1 from {table} where {where});",
    ])


def main(workbook_path, out_path):
    wb = openpyxl.load_workbook(workbook_path, data_only=True)
    parts = [
        "-- Generated by scripts/build_migration.py — do not edit by hand.",
        f"-- Source workbook: {Path(workbook_path).name}",
        "--",
        "-- Every statement is an upsert, so this is safe to run more than once.",
        "-- Nothing is deleted: a row missing from the workbook is left as it is.",
        "",
    ]

    for spec in TABLES:
        rows = read_sheet(wb, spec["sheet"])
        if not rows:
            parts.append(f"-- {spec['sheet']}: nothing to import.\n")
            continue

        parts.append(f"/* {spec['title']} — {len(rows)} row(s) */\n")

        for record in rows:
            for derived, source in (spec.get("derive") or {}).items():
                if not record.get(derived) and record.get(source):
                    record[derived] = slugify(str(record[source]))

            columns = list(spec["columns"])
            for derived in (spec.get("derive") or {}):
                if derived not in columns:
                    columns.append(derived)

            parts.append(upsert(spec["table"], spec["key"], columns, record))
            parts.append("")

    Path(out_path).write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        raise SystemExit(1)
    main(sys.argv[1], sys.argv[2])
